# docker-compose.yml
version: '3.8'

services:
  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./streamlit_app/uploads:/app/uploads
      - ./streamlit_app/detections:/app/detections
    environment:
      - YOLO_MODEL=yolov8l.pt
      - CONFIDENCE_DEFAULT=0.25
      - MAX_IMAGE_SIZE=5242880
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  fastapi:
    build:
      context: ./fastapi_app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app/static:/app/static
    environment:
      - DEBUG=1
      - MAX_UPLOAD_SIZE=5242880
      - YOLO_MODEL=yolov8l.pt
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  flask:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./flask_app/static:/app/static
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - SECRET_KEY=your-secret-key-here
      - YOLO_MODEL=yolov8l.pt
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]